### ISSUE TITLE
El SDK siempre retorna error al momento de consultar clientes, planes, lista de bancos, etc

### ISSUE THREAD

**Issue by gustavoagalvis** [epayco/sdk-.net#1]
al invocar el metodo FINDCUSTOMER arroja el siguiente error (sucede tambien al consultar planes, lista de bancos, suscripciones)

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.\r\n   en Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   en Newtonsoft.Json.JsonTextReader.Read()\r\n   en Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   en Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   en Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   en Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   en Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   en Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)\r\n   en EpaycoSdk.Epayco.FindCustomer(String id_customer)

**Comment by alejo9424** [comment]
@gustavoagalvis Gracias por reportar el incidente, se realizó la respectiva corrección y ya se encuentra desplegada la actualización con la solución en la versión 1.0.10.
